PROJNAME=mwlike8
PROJPATH=G:/Data/MainData/KNOWL~EI/COMPU~LR/gui/mwlike8/backup/EXAMP~!_/arch/CYPRE~L!/PSOCD~QT
PSOCDIR=C:\PROGRA~1\CYPRES~2\PSOCDE~1
ASMFLAGS=-g
ENABLE_24MHZ_WARNING=0
ENABLE_ALIGN_SHIFT=0
LIBS=
LIB_PATH=
INCLUDE_PATH=C:/PROGRA~1/CYPRES~2/PSOCDE~1/tools/include/CY8C27~1
CDEFINES=
CSRCS= cirbuf.c fork.c gpio.c main.c maink.c mw_pro1.c printf.c sched.c serial.c setup.c softirq.c srvfunc.c srvmain.c time.c timer.c twlm6023.c
LIBCSRCS=
ASMSRCS=
LIBASMSRCS= psocconfig.asm psocconfigtbl.asm psocgpioint.asm timer8_1.asm timer8_1int.asm uart_1.asm uart_1int.asm uart_1plus.asm
OBJECT_SOURCES= cirbuf.c fork.c gpio.c main.c maink.c mw_pro1.c printf.c sched.c serial.c setup.c softirq.c srvfunc.c srvmain.c time.c timer.c twlm6023.c
FILLVALUE=0x30
LASTROM=0x3fff
LASTRAM=0xff
RELSTART=0x100
CODECOMPRESSOR= 
MORE_CFLAGS=  
BASEDEVICE=CY8C27000
