/******************************************************************************
*  Generated by PSoC Designer ver 4.1 b931 : 21 January, 2004
******************************************************************************/
/*
*   PSoCGPIOINT.h
*   Data: 04 June, 2002
*   Copyright Cypress MicroSystems 2002
*
*  This file is generated by the Device Editor on Application Generation.
*  It contains equates that are useful in writing code relating to GPIO
*  related values.
*  
*  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
*  Edits to this file will not be preserved.
*/
#include <m8c.h>
// Port_3_3 address and mask defines
#pragma	ioport	Port_3_3_Data_ADDR:	0xc
BYTE			Port_3_3_Data_ADDR;
#pragma	ioport	Port_3_3_DriveMode_0_ADDR:	0x10c
BYTE			Port_3_3_DriveMode_0_ADDR;
#pragma	ioport	Port_3_3_DriveMode_1_ADDR:	0x10d
BYTE			Port_3_3_DriveMode_1_ADDR;
#pragma	ioport	Port_3_3_DriveMode_2_ADDR:	0xf
BYTE			Port_3_3_DriveMode_2_ADDR;
#pragma	ioport	Port_3_3_GlobalSelect_ADDR:	0xe
BYTE			Port_3_3_GlobalSelect_ADDR;
#pragma	ioport	Port_3_3_IntCtrl_0_ADDR:	0x10e
BYTE			Port_3_3_IntCtrl_0_ADDR;
#pragma	ioport	Port_3_3_IntCtrl_1_ADDR:	0x10f
BYTE			Port_3_3_IntCtrl_1_ADDR;
#pragma	ioport	Port_3_3_IntEn_ADDR:	0xd
BYTE			Port_3_3_IntEn_ADDR;
#define Port_3_3_MASK 0x8
// Port_3_1 address and mask defines
#pragma	ioport	Port_3_1_Data_ADDR:	0xc
BYTE			Port_3_1_Data_ADDR;
#pragma	ioport	Port_3_1_DriveMode_0_ADDR:	0x10c
BYTE			Port_3_1_DriveMode_0_ADDR;
#pragma	ioport	Port_3_1_DriveMode_1_ADDR:	0x10d
BYTE			Port_3_1_DriveMode_1_ADDR;
#pragma	ioport	Port_3_1_DriveMode_2_ADDR:	0xf
BYTE			Port_3_1_DriveMode_2_ADDR;
#pragma	ioport	Port_3_1_GlobalSelect_ADDR:	0xe
BYTE			Port_3_1_GlobalSelect_ADDR;
#pragma	ioport	Port_3_1_IntCtrl_0_ADDR:	0x10e
BYTE			Port_3_1_IntCtrl_0_ADDR;
#pragma	ioport	Port_3_1_IntCtrl_1_ADDR:	0x10f
BYTE			Port_3_1_IntCtrl_1_ADDR;
#pragma	ioport	Port_3_1_IntEn_ADDR:	0xd
BYTE			Port_3_1_IntEn_ADDR;
#define Port_3_1_MASK 0x2
// Port_5_3 address and mask defines
#pragma	ioport	Port_5_3_Data_ADDR:	0x14
BYTE			Port_5_3_Data_ADDR;
#pragma	ioport	Port_5_3_DriveMode_0_ADDR:	0x114
BYTE			Port_5_3_DriveMode_0_ADDR;
#pragma	ioport	Port_5_3_DriveMode_1_ADDR:	0x115
BYTE			Port_5_3_DriveMode_1_ADDR;
#pragma	ioport	Port_5_3_DriveMode_2_ADDR:	0x17
BYTE			Port_5_3_DriveMode_2_ADDR;
#pragma	ioport	Port_5_3_GlobalSelect_ADDR:	0x16
BYTE			Port_5_3_GlobalSelect_ADDR;
#pragma	ioport	Port_5_3_IntCtrl_0_ADDR:	0x116
BYTE			Port_5_3_IntCtrl_0_ADDR;
#pragma	ioport	Port_5_3_IntCtrl_1_ADDR:	0x117
BYTE			Port_5_3_IntCtrl_1_ADDR;
#pragma	ioport	Port_5_3_IntEn_ADDR:	0x15
BYTE			Port_5_3_IntEn_ADDR;
#define Port_5_3_MASK 0x8
