/******************************************************************************
*  Generated by PSoC Designer ver 4.2  b1013 : 02 September, 2004
******************************************************************************/
/*
*   PSoCGPIOINT.h
*   Data: 04 June, 2002
*   Copyright Cypress MicroSystems 2002
*
*  This file is generated by the Device Editor on Application Generation.
*  It contains equates that are useful in writing code relating to GPIO
*  related values.
*  
*  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
*  Edits to this file will not be preserved.
*/
#include <m8c.h>
// Port_5_1 address and mask defines
#pragma	ioport	Port_5_1_Data_ADDR:	0x14
BYTE			Port_5_1_Data_ADDR;
#pragma	ioport	Port_5_1_DriveMode_0_ADDR:	0x114
BYTE			Port_5_1_DriveMode_0_ADDR;
#pragma	ioport	Port_5_1_DriveMode_1_ADDR:	0x115
BYTE			Port_5_1_DriveMode_1_ADDR;
#pragma	ioport	Port_5_1_DriveMode_2_ADDR:	0x17
BYTE			Port_5_1_DriveMode_2_ADDR;
#pragma	ioport	Port_5_1_GlobalSelect_ADDR:	0x16
BYTE			Port_5_1_GlobalSelect_ADDR;
#pragma	ioport	Port_5_1_IntCtrl_0_ADDR:	0x116
BYTE			Port_5_1_IntCtrl_0_ADDR;
#pragma	ioport	Port_5_1_IntCtrl_1_ADDR:	0x117
BYTE			Port_5_1_IntCtrl_1_ADDR;
#pragma	ioport	Port_5_1_IntEn_ADDR:	0x15
BYTE			Port_5_1_IntEn_ADDR;
#define Port_5_1_MASK 0x2
// Port_5_0 address and mask defines
#pragma	ioport	Port_5_0_Data_ADDR:	0x14
BYTE			Port_5_0_Data_ADDR;
#pragma	ioport	Port_5_0_DriveMode_0_ADDR:	0x114
BYTE			Port_5_0_DriveMode_0_ADDR;
#pragma	ioport	Port_5_0_DriveMode_1_ADDR:	0x115
BYTE			Port_5_0_DriveMode_1_ADDR;
#pragma	ioport	Port_5_0_DriveMode_2_ADDR:	0x17
BYTE			Port_5_0_DriveMode_2_ADDR;
#pragma	ioport	Port_5_0_GlobalSelect_ADDR:	0x16
BYTE			Port_5_0_GlobalSelect_ADDR;
#pragma	ioport	Port_5_0_IntCtrl_0_ADDR:	0x116
BYTE			Port_5_0_IntCtrl_0_ADDR;
#pragma	ioport	Port_5_0_IntCtrl_1_ADDR:	0x117
BYTE			Port_5_0_IntCtrl_1_ADDR;
#pragma	ioport	Port_5_0_IntEn_ADDR:	0x15
BYTE			Port_5_0_IntEn_ADDR;
#define Port_5_0_MASK 0x1
// AnalogOutBuf_3 address and mask defines
#pragma	ioport	AnalogOutBuf_3_Data_ADDR:	0x0
BYTE			AnalogOutBuf_3_Data_ADDR;
#pragma	ioport	AnalogOutBuf_3_DriveMode_0_ADDR:	0x100
BYTE			AnalogOutBuf_3_DriveMode_0_ADDR;
#pragma	ioport	AnalogOutBuf_3_DriveMode_1_ADDR:	0x101
BYTE			AnalogOutBuf_3_DriveMode_1_ADDR;
#pragma	ioport	AnalogOutBuf_3_DriveMode_2_ADDR:	0x3
BYTE			AnalogOutBuf_3_DriveMode_2_ADDR;
#pragma	ioport	AnalogOutBuf_3_GlobalSelect_ADDR:	0x2
BYTE			AnalogOutBuf_3_GlobalSelect_ADDR;
#pragma	ioport	AnalogOutBuf_3_IntCtrl_0_ADDR:	0x102
BYTE			AnalogOutBuf_3_IntCtrl_0_ADDR;
#pragma	ioport	AnalogOutBuf_3_IntCtrl_1_ADDR:	0x103
BYTE			AnalogOutBuf_3_IntCtrl_1_ADDR;
#pragma	ioport	AnalogOutBuf_3_IntEn_ADDR:	0x1
BYTE			AnalogOutBuf_3_IntEn_ADDR;
#define AnalogOutBuf_3_MASK 0x4
