; Generated by PSoC Designer ver 4.2  b1013 : 02 September, 2004
;
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_aaa_Bank1
export LoadConfigTBL_aaa_Bank0
export LoadConfigTBL_aaa_Ordered
AREA lit(rom, rel)
LoadConfigTBL_aaa_Ordered:
;  Ordered Global Register values
	M8C_SetBank1
	mov	reg[00h], 8ah		; Port_0_DriveMode_0 register (PRT0DM0)
	mov	reg[01h], 75h		; Port_0_DriveMode_1 register (PRT0DM1)
	M8C_SetBank0
	mov	reg[03h], 75h		; Port_0_DriveMode_2 register (PRT0DM2)
	mov	reg[02h], 00h		; Port_0_GlobalSelect register (PRT0GS)
	M8C_SetBank1
	mov	reg[02h], 00h		; Port_0_IntCtrl_0 register (PRT0IC0)
	mov	reg[03h], 00h		; Port_0_IntCtrl_1 register (PRT0IC1)
	M8C_SetBank0
	mov	reg[01h], 00h		; Port_0_IntEn register (PRT0IE)
	M8C_SetBank1
	mov	reg[04h], 00h		; Port_1_DriveMode_0 register (PRT1DM0)
	mov	reg[05h], ffh		; Port_1_DriveMode_1 register (PRT1DM1)
	M8C_SetBank0
	mov	reg[07h], a3h		; Port_1_DriveMode_2 register (PRT1DM2)
	mov	reg[06h], 00h		; Port_1_GlobalSelect register (PRT1GS)
	M8C_SetBank1
	mov	reg[06h], 00h		; Port_1_IntCtrl_0 register (PRT1IC0)
	mov	reg[07h], 00h		; Port_1_IntCtrl_1 register (PRT1IC1)
	M8C_SetBank0
	mov	reg[05h], 00h		; Port_1_IntEn register (PRT1IE)
	M8C_SetBank1
	mov	reg[08h], 82h		; Port_2_DriveMode_0 register (PRT2DM0)
	mov	reg[09h], 75h		; Port_2_DriveMode_1 register (PRT2DM1)
	M8C_SetBank0
	mov	reg[0bh], 00h		; Port_2_DriveMode_2 register (PRT2DM2)
	mov	reg[0ah], 00h		; Port_2_GlobalSelect register (PRT2GS)
	M8C_SetBank1
	mov	reg[0ah], 00h		; Port_2_IntCtrl_0 register (PRT2IC0)
	mov	reg[0bh], 00h		; Port_2_IntCtrl_1 register (PRT2IC1)
	M8C_SetBank0
	mov	reg[09h], 00h		; Port_2_IntEn register (PRT2IE)
	M8C_SetBank1
	mov	reg[0ch], 8ah		; Port_3_DriveMode_0 register (PRT3DM0)
	mov	reg[0dh], 7fh		; Port_3_DriveMode_1 register (PRT3DM1)
	M8C_SetBank0
	mov	reg[0fh], 00h		; Port_3_DriveMode_2 register (PRT3DM2)
	mov	reg[0eh], a0h		; Port_3_GlobalSelect register (PRT3GS)
	M8C_SetBank1
	mov	reg[0eh], 00h		; Port_3_IntCtrl_0 register (PRT3IC0)
	mov	reg[0fh], 00h		; Port_3_IntCtrl_1 register (PRT3IC1)
	M8C_SetBank0
	mov	reg[0dh], 00h		; Port_3_IntEn register (PRT3IE)
	M8C_SetBank1
	mov	reg[10h], aah		; Port_4_DriveMode_0 register (PRT4DM0)
	mov	reg[11h], 5fh		; Port_4_DriveMode_1 register (PRT4DM1)
	M8C_SetBank0
	mov	reg[13h], 00h		; Port_4_DriveMode_2 register (PRT4DM2)
	mov	reg[12h], 00h		; Port_4_GlobalSelect register (PRT4GS)
	M8C_SetBank1
	mov	reg[12h], 00h		; Port_4_IntCtrl_0 register (PRT4IC0)
	mov	reg[13h], 00h		; Port_4_IntCtrl_1 register (PRT4IC1)
	M8C_SetBank0
	mov	reg[11h], 00h		; Port_4_IntEn register (PRT4IE)
	M8C_SetBank1
	mov	reg[14h], 00h		; Port_5_DriveMode_0 register (PRT5DM0)
	mov	reg[15h], 0fh		; Port_5_DriveMode_1 register (PRT5DM1)
	M8C_SetBank0
	mov	reg[17h], 00h		; Port_5_DriveMode_2 register (PRT5DM2)
	mov	reg[16h], 00h		; Port_5_GlobalSelect register (PRT5GS)
	M8C_SetBank1
	mov	reg[16h], 03h		; Port_5_IntCtrl_0 register (PRT5IC0)
	mov	reg[17h], 03h		; Port_5_IntCtrl_1 register (PRT5IC1)
	M8C_SetBank0
	mov	reg[15h], 03h		; Port_5_IntEn register (PRT5IE)
	M8C_SetBank1
	mov	reg[18h], 00h		; Port_6_DriveMode_0 register (PRT6DM0)
	mov	reg[19h], 00h		; Port_6_DriveMode_1 register (PRT6DM1)
	M8C_SetBank0
	mov	reg[1bh], 00h		; Port_6_DriveMode_2 register (PRT6DM2)
	mov	reg[1ah], 00h		; Port_6_GlobalSelect register (PRT6GS)
	M8C_SetBank1
	mov	reg[1ah], 00h		; Port_6_IntCtrl_0 register (PRT6IC0)
	mov	reg[1bh], 00h		; Port_6_IntCtrl_1 register (PRT6IC1)
	M8C_SetBank0
	mov	reg[19h], 00h		; Port_6_IntEn register (PRT6IE)
	M8C_SetBank1
	mov	reg[1ch], 00h		; Port_7_DriveMode_0 register (PRT7DM0)
	mov	reg[1dh], 00h		; Port_7_DriveMode_1 register (PRT7DM1)
	M8C_SetBank0
	mov	reg[1fh], 00h		; Port_7_DriveMode_2 register (PRT7DM2)
	mov	reg[1eh], 00h		; Port_7_GlobalSelect register (PRT7GS)
	M8C_SetBank1
	mov	reg[1eh], 00h		; Port_7_IntCtrl_0 register (PRT7IC0)
	mov	reg[1fh], 00h		; Port_7_IntCtrl_1 register (PRT7IC1)
	M8C_SetBank0
	mov	reg[1dh], 00h		; Port_7_IntEn register (PRT7IE)
	ret
LoadConfigTBL_aaa_Bank0:
;  Global Register values
	db		60h, 28h		; AnalogColumnInputSelect register (AMX_IN)
	db		66h, 00h		; AnalogComparatorControl1 register (CMP_CR1)
	db		63h, 15h		; AnalogReferenceControl register (ARF_CR)
	db		65h, 00h		; AnalogSyncControl register (ASY_CR)
	db		e6h, 48h		; DecimatorControl_0 register (DEC_CR0)
	db		e7h, 08h		; DecimatorControl_1 register (DEC_CR1)
	db		d6h, 00h		; I2CConfig register (I2CCFG)
	db		b0h, 0ch		; Row_0_InputMux register (RDI0RI)
	db		b1h, 00h		; Row_0_InputSync register (RDI0SYN)
	db		b2h, 00h		; Row_0_LogicInputAMux register (RDI0IS)
	db		b3h, 33h		; Row_0_LogicSelect_0 register (RDI0LT0)
	db		b4h, 33h		; Row_0_LogicSelect_1 register (RDI0LT1)
	db		b5h, 00h		; Row_0_OutputDrive_0 register (RDI0SRO0)
	db		b6h, 00h		; Row_0_OutputDrive_1 register (RDI0SRO1)
	db		b8h, 55h		; Row_1_InputMux register (RDI1RI)
	db		b9h, 00h		; Row_1_InputSync register (RDI1SYN)
	db		bah, 10h		; Row_1_LogicInputAMux register (RDI1IS)
	db		bbh, 33h		; Row_1_LogicSelect_0 register (RDI1LT0)
	db		bch, 33h		; Row_1_LogicSelect_1 register (RDI1LT1)
	db		bdh, 00h		; Row_1_OutputDrive_0 register (RDI1SRO0)
	db		beh, 80h		; Row_1_OutputDrive_1 register (RDI1SRO1)
	db		c0h, 00h		; Row_2_InputMux register (RDI2RI)
	db		c1h, 00h		; Row_2_InputSync register (RDI2SYN)
	db		c2h, 20h		; Row_2_LogicInputAMux register (RDI2IS)
	db		c3h, 33h		; Row_2_LogicSelect_0 register (RDI2LT0)
	db		c4h, 33h		; Row_2_LogicSelect_1 register (RDI3LT1)
	db		c5h, 00h		; Row_2_OutputDrive_0 register (RDI2SRO0)
	db		c6h, 00h		; Row_2_OutputDrive_1 register (RDI2SRO1)
	db		c8h, 55h		; Row_3_InputMux register (RDI3RI)
	db		c9h, 00h		; Row_3_InputSync register (RDI3SYN)
	db		cah, 30h		; Row_3_LogicInputAMux register (RDI3IS)
	db		cbh, 33h		; Row_3_LogicSelect_0 register (RDI3LT0)
	db		cch, 33h		; Row_3_LogicSelect_1 register (RDI3LT1)
	db		cdh, 00h		; Row_3_OutputDrive_0 register (RDI3SRO0)
	db		ceh, 00h		; Row_3_OutputDrive_1 register (RDI3SRO1)
	db		6ch, 00h		; TMP_DR0 register (TMP_DR0)
	db		6dh, 00h		; TMP_DR1 register (TMP_DR1)
	db		6eh, 00h		; TMP_DR2 register (TMP_DR2)
	db		6fh, 00h		; TMP_DR3 register (TMP_DR3)
;  Instance name ADCINC14_1, User Module ADCINC14
;       Instance name ADCINC14_1, Block Name ADC(ASC12)
	db		88h, 90h		;ADCINC14_1_bfAtoDcr0       (ASC12CR0)
	db		89h, 00h		;ADCINC14_1_bfAtoDcr1       (ASC12CR1)
	db		8ah, 60h		;ADCINC14_1_bfAtoDcr2       (ASC12CR2)
	db		8bh, f0h		;ADCINC14_1_bfAtoDcr3       (ASC12CR3)
;       Instance name ADCINC14_1, Block Name CNT(DBB00)
	db		23h, 00h		;ADCINC14_1_bCounter_CR0    (DBB00CR0)
	db		21h, 00h		;ADCINC14_1_bPeriod         (DBB00DR1)
	db		22h, 00h		;ADCINC14_1_bCompare        (DBB00DR2)
;       Instance name ADCINC14_1, Block Name PWM24_ISB(DBB10)
	db		33h, 00h		;ADCINC14_1_fPWM_ISB_CR0    (DBB10CR0)
	db		31h, 00h		;ADCINC14_1_bPWM_Period_ISB (DBB10DR1)
	db		32h, 00h		;ADCINC14_1_bPWM_IntTime_ISB(DBB10DR2)
;       Instance name ADCINC14_1, Block Name PWM24_LSB(DCB03)
	db		2fh, 00h		;ADCINC14_1_fPWM_LSB_CR0    (DCB03CR0)
	db		2dh, 00h		;ADCINC14_1_bPWM_Period_LSB (DCB03DR1)
	db		2eh, 00h		;ADCINC14_1_bPWM_IntTime_LSB(DCB03DR2)
;       Instance name ADCINC14_1, Block Name PWM24_MSB(DBB11)
	db		37h, 00h		;ADCINC14_1_fPWM_MSB_CR0    (DBB11CR0)
	db		35h, 00h		;ADCINC14_1_bPWM_Period_MSB (DBB11DR1)
	db		36h, 00h		;ADCINC14_1_bPWM_IntTime_MSB(DBB11DR2)
;  Instance name DAC9_1, User Module DAC9
;       Instance name DAC9_1, Block Name LSB(ASD20)
	db		90h, 80h		;DAC9_1_LSB_CR0(ASD20CR0)
	db		91h, 80h		;DAC9_1_LSB_CR1(ASD20CR1)
	db		92h, 20h		;DAC9_1_LSB_CR2(ASD20CR2)
	db		93h, 30h		;DAC9_1_LSB_CR3(ASD20CR3)
;       Instance name DAC9_1, Block Name MSB(ASC10)
	db		80h, a0h		;DAC9_1_MSB_CR0(ASC10CR0)
	db		81h, 41h		;DAC9_1_MSB_CR1(ASC10CR1)
	db		82h, a0h		;DAC9_1_MSB_CR2(ASC10CR2)
	db		83h, 3ch		;DAC9_1_MSB_CR3(ASC10CR3)
;  Instance name DAC9_2, User Module DAC9
;       Instance name DAC9_2, Block Name LSB(ASD13)
	db		8ch, 80h		;DAC9_2_LSB_CR0(ASD13CR0)
	db		8dh, 80h		;DAC9_2_LSB_CR1(ASD13CR1)
	db		8eh, 20h		;DAC9_2_LSB_CR2(ASD13CR2)
	db		8fh, 30h		;DAC9_2_LSB_CR3(ASD13CR3)
;       Instance name DAC9_2, Block Name MSB(ASC23)
	db		9ch, a0h		;DAC9_2_MSB_CR0(ASC23CR0)
	db		9dh, 41h		;DAC9_2_MSB_CR1(ASC23CR1)
	db		9eh, a0h		;DAC9_2_MSB_CR2(ASC23CR2)
	db		9fh, 30h		;DAC9_2_MSB_CR3(ASC23CR3)
;  Instance name E2PROM_1, User Module E2PROM
;  Instance name PGA_1, User Module PGA
;       Instance name PGA_1, Block Name GAIN(ACB02)
	db		79h, fdh		;PGA_1_GAIN_CR0(ACB02CR0)
	db		7ah, 21h		;PGA_1_GAIN_CR1(ACB02CR1)
	db		7bh, 20h		;PGA_1_GAIN_CR2(ACB02CR2)
	db		78h, 00h		;PGA_1_GAIN_CR3(ACB02CR3)
;  Instance name Timer8_1, User Module Timer8
;       Instance name Timer8_1, Block Name TIMER8(DCB13)
	db		3fh, 04h		;Timer8_1_CONTROL_REG(DCB13CR0)
	db		3dh, a0h		;Timer8_1_PERIOD_REG(DCB13DR1)
	db		3eh, 00h		;Timer8_1_COMPARE_REG(DCB13DR2)
;  Instance name UART_1, User Module UART
;       Instance name UART_1, Block Name RX(DCB02)
	db		2bh, 00h		;UART_1_RX_CONTROL_REG(DCB02CR0)
	db		29h, 00h		;UART_1_(DCB02DR1)
	db		2ah, 00h		;UART_1_RX_BUFFER_REG (DCB02DR2)
;       Instance name UART_1, Block Name TX(DCB12)
	db		3bh, 00h		;UART_1_TX_CONTROL_REG(DCB12CR0)
	db		39h, 00h		;UART_1_TX_BUFFER_REG (DCB12DR1)
	db		3ah, 00h		;UART_1_(DCB12DR2)
	db		ffh
LoadConfigTBL_aaa_Bank1:
;  Global Register values
	db		61h, 00h		; AnalogClockSelect1 register (CLK_CR1)
	db		69h, 00h		; AnalogClockSelect2 register (CLK_CR2)
	db		60h, 41h		; AnalogColumnClockSelect register (CLK_CR0)
	db		62h, 04h		; AnalogIOControl_0 register (ABF_CR0)
	db		67h, 33h		; AnalogLUTControl0 register (ALT_CR0)
	db		68h, 33h		; AnalogLUTControl1 register (ALT_CR1)
	db		63h, 00h		; AnalogModulatorControl_0 register (AMD_CR0)
	db		66h, 00h		; AnalogModulatorControl_1 register (AMD_CR1)
	db		d1h, 00h		; GlobalDigitalInterconnect_Drive_Even_Input register (GDI_E_IN)
	db		d3h, 00h		; GlobalDigitalInterconnect_Drive_Even_Output register (GDI_E_OU)
	db		d0h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Input register (GDI_O_IN)
	db		d2h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Output register (GDI_O_OU)
	db		e1h, 5fh		; OscillatorControl_1 register (OSC_CR1)
	db		e2h, 00h		; OscillatorControl_2 register (OSC_CR2)
	db		dfh, 19h		; OscillatorControl_3 register (OSC_CR3)
	db		deh, 01h		; OscillatorControl_4 register (OSC_CR4)
	db		ddh, 00h		; OscillatorGlobalBusEnableControl register (OSC_GO_EN)
	db		e7h, 00h		; Type2Decimator_Control register (DEC_CR2)
;  Instance name ADCINC14_1, User Module ADCINC14
;       Instance name ADCINC14_1, Block Name ADC(ASC12)
;       Instance name ADCINC14_1, Block Name CNT(DBB00)
	db		20h, 21h		;ADCINC14_1_fCounterFN      (DBB00FN)
	db		21h, 65h		;ADCINC14_1_fCounterSL      (DBB00IN)
	db		22h, 40h		;ADCINC14_1_fCounterOS      (DBB00OU)
;       Instance name ADCINC14_1, Block Name PWM24_ISB(DBB10)
	db		30h, 01h		;ADCINC14_1_bfPWM_ISB_FN    (DBB10FN)
	db		31h, 35h		;ADCINC14_1_(DBB10IN)
	db		32h, 40h		;ADCINC14_1_(DBB10OU)
;       Instance name ADCINC14_1, Block Name PWM24_LSB(DCB03)
	db		2ch, 01h		;ADCINC14_1_bfPWM_LSB_FN    (DCB03FN)
	db		2dh, 15h		;ADCINC14_1_(DCB03IN)
	db		2eh, 40h		;ADCINC14_1_(DCB03OU)
;       Instance name ADCINC14_1, Block Name PWM24_MSB(DBB11)
	db		34h, 21h		;ADCINC14_1_bfPWM_MSB_FN    (DBB11FN)
	db		35h, 35h		;ADCINC14_1_(DBB11IN)
	db		36h, 40h		;ADCINC14_1_(DBB11OU)
;  Instance name DAC9_1, User Module DAC9
;       Instance name DAC9_1, Block Name LSB(ASD20)
;       Instance name DAC9_1, Block Name MSB(ASC10)
;  Instance name DAC9_2, User Module DAC9
;       Instance name DAC9_2, Block Name LSB(ASD13)
;       Instance name DAC9_2, Block Name MSB(ASC23)
;  Instance name E2PROM_1, User Module E2PROM
;  Instance name PGA_1, User Module PGA
;       Instance name PGA_1, Block Name GAIN(ACB02)
;  Instance name Timer8_1, User Module Timer8
;       Instance name Timer8_1, Block Name TIMER8(DCB13)
	db		3ch, 20h		;Timer8_1_FUNC_REG(DCB13FN)
	db		3dh, 07h		;Timer8_1_INPUT_REG(DCB13IN)
	db		3eh, 40h		;Timer8_1_OUTPUT_REG(DCB13OU)
;  Instance name UART_1, User Module UART
;       Instance name UART_1, Block Name RX(DCB02)
	db		28h, 05h		;UART_1_RX_FUNC_REG   (DCB02FN)
	db		29h, d1h		;UART_1_RX_INPUT_REG  (DCB02IN)
	db		2ah, 40h		;UART_1_RX_OUTPUT_REG (DCB02OU)
;       Instance name UART_1, Block Name TX(DCB12)
	db		38h, 0dh		;UART_1_TX_FUNC_REG   (DCB12FN)
	db		39h, 01h		;UART_1_TX_INPUT_REG  (DCB12IN)
	db		3ah, 47h		;UART_1_TX_OUTPUT_REG (DCB12OU)
	db		ffh


; PSoC Configuration file trailer PsocConfig.asm
